name: flutterbeginner
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  http: ^0.12.2
  dio: ^3.0.10
  path_provider: ^1.6.11
  simple_animations: ^2.2.1
  avatar_glow: ^1.2.0
  flutter_rating_bar: ^3.2.0+1
  #  flutter_datetime_picker:
  shared_preferences: ^0.5.12
  permission_handler: ^5.0.1
  image_picker: ^0.6.7+11
  pinput: ^0.2.4
  flutter_staggered_grid_view: ^0.3.2
  google_maps_flutter: ^1.0.2
  geolocator: ^6.0.0
  webview_flutter: ^1.0.5
  barcode_scan: ^3.0.1
  video_player: ^0.11.0
  #  flutter_local_notifications: ^2.0.0
  contacts_service: ^0.4.6
  sms: ^0.2.4
  storage_path: ^0.2.0
  photo_view: ^0.10.2
  open_file: ^3.0.3
  esys_flutter_share: ^1.0.2
  call_log: ^2.1.0
  audioplayers: ^0.16.2
  local_auth: ^0.6.2+3
  device_info: ^0.4.2+8
  provider: ^4.3.2
  shimmer: ^1.1.1
  carousel_slider: ^2.2.1
  page_indicator: ^0.3.0
  font_awesome_flutter: ^8.8.1
  sliver_fab: ^1.0.0
  youtube_player_flutter: ^7.0.0+7
  cached_network_image: ^2.2.0+1
  timeline_tile: ^1.0.0
  fancy_bottom_navigation: ^0.3.2
  titled_navigation_bar: ^4.1.0
  bubble_tab_indicator: ^0.1.4
  intro_views_flutter: ^2.8.2
  #  convex_bottom_bar: ^2.6.0
  splashscreen: ^1.3.5
  flutter_slidable: ^0.5.7
  pull_to_refresh: ^1.6.1
  flutter_search_bar: ^2.1.0
#  wave: ^0.1.0
  drawerbehavior: ^1.1.4
  animated_floatactionbuttons: ^0.1.0
  url_launcher: ^5.5.0
  animator: ^2.0.1
  rect_getter: ^0.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/local_file/
    - assets/fonts/
    - lib/view/
    - lib/view/alltask/
    - lib/view/api/
    - lib/view/bottombar/
    - lib/view/collapsetoolbar/
    - lib/view/details/
    - lib/view/example/
    - lib/view/firebase/
    - lib/view/github/
    - lib/view/home/
    - lib/view/list/
    - lib/view/local/
    - lib/view/local/audio/
    - lib/view/local/contact/
    - lib/view/local/document/
    - lib/view/local/image/
    - lib/view/local/video/
    - lib/view/login/
    - lib/view/navigation/
    - lib/view/onboarding/
    - lib/view/profile/
    - lib/view/pulltorefresh/
    - lib/view/settings/
    - lib/view/splash/
    - lib/view/sqflite/
    - lib/view/tabbar/
    - lib/view/widgets/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.otf
          weight: 600
    - family: Zillaslab
      fonts:
        - asset: assets/fonts/Zillaslab-bold.ttf
        - asset: assets/fonts/Zillaslab-light.ttf
        - asset: assets/fonts/Zillaslab-medium.ttf
        - asset: assets/fonts/Zillaslab-regular.ttf
    - family: PT
      fonts:
        - asset: assets/fonts/PT-bold.ttf
        - asset: assets/fonts/PT-italic.ttf
        - asset: assets/fonts/PT-regular.ttf
