name: flutterbeginner
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

# consider running `flutter pub upgrade --major-versions`. Alternatively,
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^1.2.1
  cached_network_image: ^3.3.1
  dio: ^5.2.0
  path_provider: ^2.0.15
  simple_animations: ^5.0.1
  avatar_glow: ^3.0.1
  flutter_rating_bar: ^4.0.1
  #  flutter_datetime_picker:
  shared_preferences: ^2.1.2
  permission_handler: ^11.3.0
  flutter_storage_path: ^1.0.4
  image_picker: ^1.0.7
  pinput: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  google_maps_flutter: ^2.3.0
  geolocator: ^11.0.0
  webview_flutter: ^4.2.2
  barcode_scan2: ^4.2.4
  video_player: ^2.6.1
  flutter_local_notifications: ^17.0.0
  contacts_service: ^0.6.3
  #  sms: ^0.2.4
  #  storage_path: ^0.2.0
  #  esys_flutter_share: ^1.0.2
  photo_view: ^0.14.0
  open_file: ^3.3.1
  call_log: ^4.0.0
  #  audioplayers: ^0.17.4
  local_auth: ^2.1.6
  device_info_plus: ^10.0.1
  provider: ^6.0.5
  shimmer: ^3.0.0
  carousel_slider: ^4.2.1
  page_indicator: ^0.4.1
  font_awesome_flutter: ^10.4.0
  #  sliver_fab: ^1.0.0
  youtube_player_flutter: ^9.0.0
  #  youtube_player_iframe: ^4.0.4
  timeline_tile: ^2.0.0
  #  fancy_bottom_navigation: ^0.3.2
  #  titled_navigation_bar: ^4.1.0
  bubble_tab_indicator: ^0.1.6
  intro_views_flutter: ^3.2.0
  #  convex_bottom_bar: ^3.2.0
  #  splashscreen: ^1.3.5
  flutter_slidable: ^3.0.0
  pull_to_refresh: ^2.0.0
  easy_search_bar: ^2.5.0
  #  wave: ^0.1.0
  #  drawerbehavior: ^2.1.0
  #  animated_floatactionbuttons: ^0.1.0
  url_launcher: ^6.1.11
  animator: ^3.3.0
  rect_getter: ^1.1.0
  logger: ^2.2.0
  get: ^4.6.5
  responsive_framework: ^1.1.0
#  for web
  webview_flutter_web: ^0.2.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/local_file/
    - assets/fonts/
    - lib/view/
    - lib/view/alltask/
    - lib/view/api/
    - lib/view/bottombar/
    - lib/view/collapsetoolbar/
    - lib/view/details/
    - lib/view/example/
    - lib/view/firebase/
    - lib/view/home/
    - lib/view/list/
    - lib/view/local/
    - lib/view/local/audio/
    - lib/view/local/contact/
    - lib/view/local/document/
    - lib/view/local/image/
    - lib/view/local/video/
    - lib/view/login/
    - lib/view/navigation/
    - lib/view/onboarding/
    - lib/view/profile/
    - lib/view/pulltorefresh/
    - lib/view/settings/
    - lib/view/splash/
    - lib/view/sqflite/
    - lib/view/tabbar/
    - lib/view/widgets/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.otf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.otf
          weight: 600
    - family: Zillaslab
      fonts:
        - asset: assets/fonts/Zillaslab-bold.ttf
        - asset: assets/fonts/Zillaslab-light.ttf
        - asset: assets/fonts/Zillaslab-medium.ttf
        - asset: assets/fonts/Zillaslab-regular.ttf
    - family: PT
      fonts:
        - asset: assets/fonts/PT-bold.ttf
        - asset: assets/fonts/PT-italic.ttf
        - asset: assets/fonts/PT-regular.ttf
