name: flutterbeginner
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: any
  dio: ^3.0.9
  flutter_launcher_icons: ^0.7.3
  sqflite: any
  path_provider: ^1.6.8
  flutter_stetho: ^0.5.2
  simple_animations: ^1.3.3
  avatar_glow: any
  flutter_rating_bar: ^1.1.0
  flutter_datetime_picker: ^1.3.8
  shared_preferences: ^0.5.7
  permission_handler: ^3.0.0
  firebase_auth: ^0.16.0
  google_sign_in: ^4.4.4
  flutter_facebook_login: ^3.0.0
  flutter_twitter: ^1.1.3
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  image_picker: ^0.6.5+3
  pinput: ^0.2.0
  firebase_messaging: ^6.0.13
  firebase_database: ^3.1.5
  flutter_staggered_grid_view: ^0.3.0
  google_maps_flutter: ^0.5.27+1
  geolocator: ^5.3.1
  webview_flutter: ^0.3.21
  firebase_crashlytics: ^0.1.3+3
  barcode_scan: ^3.0.1
  video_player: ^0.10.11
  flutter_local_notifications: ^1.4.3
  contacts_service: ^0.4.6
  sms: ^0.2.0
  storage_path: ^0.2.0
  photo_view: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.3
  font_awesome_flutter: ^8.0.1


flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - local_file/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    - family: Zillaslab
      fonts:
        - asset: fonts/Zillaslab-bold.ttf
        - asset: fonts/Zillaslab-light.ttf
        - asset: fonts/Zillaslab-medium.ttf
        - asset: fonts/Zillaslab-regular.ttf
    - family: PT
      fonts:
        - asset: fonts/PT-bold.ttf
        - asset: fonts/PT-italic.ttf
        - asset: fonts/PT-regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
